;;; looking-glass-test.el --- Tests for looking-glass -*- lexical-binding: t; -*-

(require 'ert)
(require 'looking-glass)
(require 'looking-glass-convert)

(ert-deftest lg-lens-view-set-over ()
  (let ((optic (lg-car-lens)))
    (should (equal (lg-view optic '(1 . 2)) 1))
    (should (equal (lg-set optic 9 '(1 . 2)) '(9 . 2)))
    (should (equal (lg-over optic (lambda (x) (+ x 3)) '(1 . 2)) '(4 . 2)))))

(ert-deftest lg-compose-nested-pairs ()
  (let* ((nested '((1 . 2) . 3))
         (optic (lg-compose (lg-cdr-lens) (lg-car-lens))))
    (should (equal (lg-view optic nested) 2))
    (should (equal (lg-set optic 7 nested) '((1 . 7) . 3)))))

(ert-deftest lg-traversal-list-over-and-fold ()
  (let ((optic (lg-list-traversal)))
    (should (equal (lg-over optic (lambda (x) (* x 10)) '(1 2 3)) '(10 20 30)))
    (should (equal (lg-to-list-of optic '(1 2 3)) '(1 2 3)))))

(ert-deftest lg-prism-non-nil ()
  (let ((optic (lg-non-nil)))
    (should (equal (lg-preview optic 42) 42))
    (should (equal (lg-review optic 42) 42))
    (should (equal (lg-preview-result optic nil) '(nil . nil)))
    (should-not (lg-has optic nil))))

(ert-deftest lg-review-support ()
  (let* ((just (lg-just))
         (iso (lg-iso #'number-to-string #'string-to-number))
         (composed (lg-compose just iso)))
    (should (equal (lg-review just 7) '(just . 7)))
    (should (equal (lg-review iso "42") 42))
    (should (equal (lg-review composed "9") '(just . 9)))
    (should-error (lg-review (lg-list-traversal) 1))))

(ert-deftest lg-convert-list-vector-iso ()
  (let ((optic (lg-list-vector-iso)))
    (should (equal (lg-view optic '(1 2 3)) [1 2 3]))
    (should (equal (lg-review optic [1 2 3]) '(1 2 3)))
    (should (equal (lg-over optic (lambda (v) (vconcat v [4])) '(1 2 3)) '(1 2 3 4)))))

(ert-deftest lg-convert-number-string-prism ()
  (let ((optic (lg-number-string-prism)))
    (should (equal (lg-preview optic "42") 42))
    (should (equal (lg-preview optic "  -3.5 ") -3.5))
    (should-not (lg-has optic "42x"))
    (should (equal (lg-review optic 15) "15"))))

(ert-deftest lg-convert-char-string-prism ()
  (let ((optic (lg-char-string-prism)))
    (should (equal (lg-preview optic "A") ?A))
    (should-not (lg-has optic "AB"))
    (should (equal (lg-review optic ?Z) "Z"))))

(ert-deftest lg-convert-symbol-string-prism ()
  (let* ((existing (intern "lg-symbol-string-prism-test"))
         (missing-name (format "lg-missing-%s" (float-time)))
         (optic (lg-symbol-string-prism)))
    (should (equal (lg-preview optic "lg-symbol-string-prism-test") existing))
    (should-not (lg-has optic missing-name))
    (should (equal (lg-review optic 'hello) "hello"))))

(ert-deftest lg-convert-alist-plist-prism ()
  (let ((optic (lg-alist-plist-prism)))
    (should (equal (lg-preview optic '((:a . 1) (:b . nil))) '(:a 1 :b nil)))
    (should (equal (lg-review optic '(:a 1 :b nil)) '((:a . 1) (:b))))
    (should-not (lg-has optic '((:a . 1) (:a . 2))))
    (should-error (lg-review optic '(:a 1 :a 2)))))

(ert-deftest lg-preview-result-disambiguates-present-nil ()
  (let* ((optic (lg-plist-key-traversal :name))
         (present-nil '(:name nil :age 10))
         (missing '(:age 10)))
    (should (equal (lg-preview-result optic present-nil) '(t . nil)))
    (should (equal (lg-preview-result optic missing) '(nil . nil)))
    (should (lg-has optic present-nil))
    (should-not (lg-has optic missing))))

(ert-deftest lg-view-non-nil-signals ()
  (let ((optic (lg-plist-key-traversal :name)))
    (should-error (lg-view-non-nil optic '(:name nil)) :type 'lg-expected-non-nil)
    (should (equal (lg-view-non-nil optic '(:name "Ada")) "Ada"))))

(ert-deftest lg-alist-key-traversal ()
  (let ((optic (lg-alist-key-traversal "x" #'string=)))
    (should (equal (lg-preview-result optic '(("x" . nil) ("y" . 2))) '(t . nil)))
    (should (equal (lg-over optic (lambda (_v) 9) '(("x" . nil) ("y" . 2)))
                   '(("x" . 9) ("y" . 2))))))

(ert-deftest lg-vector-and-string-traversals ()
  (should (equal (lg-over (lg-vector-traversal) (lambda (x) (+ x 1)) [1 2 3]) [2 3 4]))
  (should (equal (lg-over (lg-string-traversal) #'upcase "abc") "ABC"))
  (should (equal (lg-to-list-of (lg-string-traversal) "ab") '("a" "b"))))

(ert-deftest lg-indexed-list-base-and-ops ()
  (let ((optic (lg-indexed-list-traversal)))
    (should (equal (lg-ito-list-of optic '(10 nil 30))
                   '((0 . 10) (1) (2 . 30))))
    (should (equal (lg-ipreview-result optic '(10 nil 30)) '(t . (0 . 10))))
    (should (equal (lg-ipreview-result optic '()) '(nil . nil)))
    (should (equal (lg-iover optic (lambda (i x) (if (= i 1) 99 x)) '(10 20 30))
                   '(10 99 30)))))

(ert-deftest lg-indexed-reindexing ()
  (let* ((base (lg-indexed-list-traversal))
         (shifted (lg-ireindexed (lambda (index) (+ index 10)) base)))
    (should (equal (lg-ito-list-of shifted '(4 5)) '((10 . 4) (11 . 5))))
    (should (equal (lg-iover shifted (lambda (i x) (+ i x)) '(4 5)) '(14 16)))))

(ert-deftest lg-derived-getter-and-folds ()
  (let* ((getter (lg-getter #'length))
         (list-optic (lg-list-traversal)))
    (should (equal (lg-view getter '(a b c)) 3))
    (should (equal (lg-over getter (lambda (x) (+ x 1)) '(a b c)) '(a b c)))
    (should (= (lg-foldl-of list-optic #'+ 0 '(1 2 3 4)) 10))
    (should (= (lg-ifoldl-of (lg-indexed-list-traversal)
                             (lambda (acc i x) (+ acc (* i x)))
                             0
                             '(2 3 4))
               11))
    (should (lg-any-of list-optic (lambda (x) (= x 3)) '(1 2 3)))
    (should (lg-all-of list-optic (lambda (x) (> x 0)) '(1 2 3)))
    (should (= (lg-count-of list-optic '(1 2 3)) 3))))

(ert-deftest lg-filtered-and-indexed-combinators ()
  (let* ((even (lg-filtered (lambda (x) (and (numberp x) (zerop (% x 2))))) )
         (filtered-indexed (lg-indexed-list-indices (lambda (i) (zerop (% i 2)))))
         (i-only (lg-indices (lambda (i) (eq i nil)))))
    (should (equal (lg-over even (lambda (x) (* x 10)) 2) 20))
    (should (equal (lg-over even (lambda (x) (* x 10)) 3) 3))
    (should (equal (lg-ito-list-of filtered-indexed '(10 11 12 13))
                   '((0 . 10) (2 . 12))))
    (should (equal (lg-iover filtered-indexed (lambda (_i x) (+ x 1)) '(10 11 12 13))
                   '(11 11 13 13)))
    (should (equal (lg-ito-list-of i-only 99) '((nil . 99))))))

(ert-deftest lg-non-nil-helpers-and-macros ()
  (let* ((optic (lg-required (lg-plist-key-traversal :name)))
         (pair-optic (lg-optic (lg-cdr-lens) (lg-car-lens))))
    (should (equal (lg-preview-or "unknown" optic '(:name "Ada")) "Ada"))
    (should (equal (lg-preview-or "unknown" optic '(:name nil)) "unknown"))
    (should (equal (lg-over-> '(1 . 2)
                              ((lg-car-lens) (lambda (x) (+ x 10)))
                              ((lg-cdr-lens) (lambda (x) (* x 2))))
                   '(11 . 4)))
    (should (equal (lg-set-> '(1 . 2)
                             ((lg-car-lens) 7)
                             ((lg-cdr-lens) 9))
                   '(7 . 9)))
    (should (equal (lg-view pair-optic '((1 . 2) . 3)) 2))))

(ert-deftest lg-extension-point-custom-affine-optic ()
  (let ((optic
         (lg-traversal
          (lambda (afb source applicative)
            (let ((pure (lg-applicative-pure applicative))
                  (fmap (lg-applicative-fmap applicative)))
              (if (numberp source)
                  (funcall fmap (lambda (v) (* v 2)) (funcall afb source))
                (funcall pure source)))))))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 10) 22))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 'nope) 'nope))
    (should (equal (lg-preview-result optic 10) '(t . 10)))
    (should (equal (lg-preview-result optic 'nope) '(nil . nil)))))

;;; looking-glass-test.el ends here
