;;; looking-glass-core-test.el --- Core tests for looking-glass -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'looking-glass)

(defun lg-test--random-int ()
  "Return a random integer in a small range for repeatable law tests."
  (- (random 200) 100))

(defun lg-test--random-list ()
  "Return a random list of integers."
  (let ((length (random 8))
        (result nil))
    (dotimes (_ length (nreverse result))
      (push (lg-test--random-int) result))))

(defun lg-test--random-string ()
  "Return a random lowercase ASCII string."
  (let ((length (random 16))
        (result nil))
    (dotimes (_ length (apply #'string (nreverse result)))
      (push (+ ?a (random 26)) result))))

(cl-defstruct lg-test-seq
  items)

(cl-defmethod lg-nth-get ((source lg-test-seq) index)
  (let ((items (lg-test-seq-items source)))
    (unless (and (>= index 0) (< index (length items)))
      (error "Index %s out of range" index))
    (aref items index)))

(cl-defmethod lg-nth-set ((source lg-test-seq) index new-focus)
  (let ((items (copy-sequence (lg-test-seq-items source))))
    (unless (and (>= index 0) (< index (length items)))
      (error "Index %s out of range" index))
    (aset items index new-focus)
    (make-lg-test-seq :items items)))

(cl-defstruct lg-test-dict
  alist)

(cl-defmethod lg-ix-get ((source lg-test-dict) key &optional _testfn)
  (let ((cell (assq key (lg-test-dict-alist source))))
    (if cell
        (lg-just (cdr cell))
      lg-nothing)))

(cl-defmethod lg-ix-set ((source lg-test-dict) key value &optional _testfn)
  (let ((updated nil)
        (result nil))
    (dolist (entry (lg-test-dict-alist source) (make-lg-test-dict :alist (nreverse result)))
      (if (and (not updated) (eq (car entry) key))
          (progn
            (setq updated t)
            (push (cons key value) result))
        (push entry result)))))

(cl-defmethod lg-at-set ((source lg-test-dict) key maybe &optional _testfn)
  (unless (or (lg-nothing-p maybe) (lg-just-p maybe))
    (error "Expected tagged maybe value"))
  (let ((removed (cl-remove-if (lambda (entry)
                                 (eq (car entry) key))
                               (lg-test-dict-alist source))))
    (if (lg-just-p maybe)
        (make-lg-test-dict :alist (append removed (list (cons key (cdr maybe)))))
      (make-lg-test-dict :alist removed))))

(ert-deftest lg-lens-view-set-over ()
  (let ((optic lg-car))
    (should (equal (lg-view optic '(1 . 2)) 1))
    (should (equal (lg-set optic 9 '(1 . 2)) '(9 . 2)))
    (should (equal (lg-over optic (lambda (x) (+ x 3)) '(1 . 2)) '(4 . 2)))))

(ert-deftest lg-generic-dispatch-extension-points ()
  (let* ((seq (make-lg-test-seq :items [1 2 3]))
         (dict (make-lg-test-dict :alist '((:name . "Ada") (:age . 10)))))
    (should (equal (lg-view (lg-nth 1) seq) 2))
    (should (equal (lg-test-seq-items (lg-set (lg-nth 1) 9 seq)) [1 9 3]))

    (should (equal (lg-preview (lg-ix :name) dict) (lg-just "Ada")))
    (should (equal (lg-preview (lg-ix :missing) dict) lg-nothing))
    (should (equal (lg-test-dict-alist (lg-set (lg-ix :age) 11 dict))
                   '((:name . "Ada") (:age . 11))))
    (should (equal (lg-test-dict-alist (lg-set (lg-at :city) (lg-just "London") dict))
                   '((:name . "Ada") (:age . 10) (:city . "London"))))
    (should (equal (lg-test-dict-alist (lg-set (lg-at :age) lg-nothing dict))
                   '((:name . "Ada"))))))

(ert-deftest lg-compose-nested-pairs ()
  (let* ((nested '((1 . 2) . 3))
         (optic (lg-compose lg-car lg-cdr)))
    (should (equal (lg-view optic nested) 2))
    (should (equal (lg-set optic 7 nested) '((1 . 7) . 3)))))

(ert-deftest lg-compose-ordering ()
  (let ((nested '((1 . 2) . 3)))
    (should (equal (lg-view (lg-compose lg-car lg-cdr) nested) 2))
    (should-error (lg-view (lg-compose lg-cdr lg-car) nested))))

(ert-deftest lg-traversal-list-over-and-fold ()
  (let ((optic lg-list))
    (should (equal (lg-over optic (lambda (x) (* x 10)) '(1 2 3)) '(10 20 30)))
    (should (equal (lg-to-list-of optic '(1 2 3)) '(1 2 3)))))

(ert-deftest lg-prism-non-nil ()
  (let ((optic lg-non-nil))
    (should (equal (lg-preview optic 42) (lg-just 42)))
    (should (equal (lg-review optic 42) 42))
    (should (equal (lg-preview optic nil) lg-nothing))
    (should-not (lg-has optic nil))))

(ert-deftest lg-bool-and-unbool-helpers ()
  (should (eq (lg-bool-value lg-true) t))
  (should (eq (lg-bool-value lg-false) nil))
  (should (eq (lg-bool t) lg-true))
  (should (eq (lg-bool nil) lg-false))
  (should (eq (lg-view lg-unbool lg-true) t))
  (should (eq (lg-view lg-unbool lg-false) nil))
  (should (eq (lg-review lg-unbool t) lg-true))
  (should (eq (lg-review lg-unbool nil) lg-false))
  (should (eq (lg-view lg-not lg-true) lg-false))
  (should (eq (lg-view lg-not lg-false) lg-true))
  (should (eq (lg-view lg-not t) nil))
  (should (eq (lg-view lg-not nil) t))
  (should (eq (lg-review lg-not lg-true) lg-false))
  (should (eq (lg-review lg-not t) nil))
  (should-error (lg-view lg-not 'nope))
  (should-error (lg-bool-value 'nope))
  (should-error (lg-bool 1)))

(ert-deftest lg-review-support ()
  (let* ((just lg-just-o)
         (iso (lg-iso #'number-to-string #'string-to-number))
         (composed (lg-compose just iso)))
    (should (equal (lg-review just 7) '(lg-just . 7)))
    (should (equal (lg-review iso "42") 42))
    (should (equal (lg-review composed "9") '(lg-just . 9)))
    (should-error (lg-review lg-list 1))))

(ert-deftest lg-reverse-reviewed-optics ()
  (let* ((iso (lg-iso #'number-to-string #'string-to-number))
         (reversed (lg-re iso))
         (reversed-lens (lg-re lg-car))
         (reversed-prism (lg-re lg-non-nil)))
    (should (equal (lg-view reversed "42") 42))
    (should (equal (lg-review reversed 7) "7"))
    (should (equal (lg-over reversed (lambda (n) (+ n 1)) "41") "42"))
    (should (equal (lg-view reversed-lens 7) '(7)))
    (should (equal (lg-review reversed-lens '(7 . 9)) 7))
    (should (equal (lg-view reversed-prism 42) 42))
    (should (equal (lg-review reversed-prism 42) 42))
    (should-error (lg-view (lg-re lg-list) '(1 2 3)))))

(ert-deftest lg-convert-list-vector-iso ()
  (let ((optic lg-list->vector))
    (should (equal (lg-view optic '(1 2 3)) [1 2 3]))
    (should (equal (lg-review optic [1 2 3]) '(1 2 3)))
    (should (equal (lg-over optic (lambda (v) (vconcat v [4])) '(1 2 3)) '(1 2 3 4)))))

(ert-deftest lg-grate-transpose-example ()
  (let* ((transpose
          (lg-grate
           (lambda (build)
             (cons (cons (funcall build (lambda (s) (car (car s))))
                         (funcall build (lambda (s) (car (cdr s)))))
                   (cons (funcall build (lambda (s) (cdr (car s))))
                         (funcall build (lambda (s) (cdr (cdr s)))))))))
         (source '((1 . 2) . (3 . 4))))
    (should (equal (lg-over transpose #'identity source)
                   '((1 . 3) . (2 . 4))))
    (should (equal (lg-set transpose 0 source)
                   '((0 . 0) . (0 . 0))))
    (should-error (lg-preview transpose source))))

(ert-deftest lg-convert-number-string-prism ()
  (let ((optic lg-number-string))
    (should (equal (lg-preview optic "42") (lg-just 42)))
    (should (equal (lg-preview optic "  -3.5 ") (lg-just -3.5)))
    (should-not (lg-has optic "42x"))
    (should (equal (lg-review optic 15) "15"))))

(ert-deftest lg-convert-char-string-prism ()
  (let ((optic lg-char-string))
    (should (equal (lg-preview optic "A") (lg-just ?A)))
    (should-not (lg-has optic "AB"))
    (should (equal (lg-review optic ?Z) "Z"))))

(ert-deftest lg-convert-symbol-string-prism ()
  (let* ((existing (intern "lg-symbol-string-test"))
         (missing-name (format "lg-unknown-%s" (float-time)))
         (optic lg-symbol-string))
    (should (equal (lg-preview optic "lg-symbol-string-test") (lg-just existing)))
    (should-not (lg-has optic missing-name))
    (should (equal (lg-review optic 'hello) "hello"))))

(ert-deftest lg-convert-alist-plist-prism ()
  (let ((optic lg-alist-plist))
    (should (equal (lg-preview optic '((:a . 1) (:b . nil))) (lg-just '(:a 1 :b nil))))
    (should (equal (lg-review optic '(:a 1 :b nil)) '((:a . 1) (:b))))
    (should-not (lg-has optic '((:a . 1) (:a . 2))))
    (should-error (lg-review optic '(:a 1 :a 2)))))

(ert-deftest lg-either-core-and-prisms ()
  (should (lg-either-p (lg-left 1)))
  (should (lg-either-p (lg-right nil)))
  (should-not (lg-either-p 42))
  (should (= (lg-either-value (lg-left 5)) 5))

  (should (equal (lg-preview lg-left-o (lg-left 10)) (lg-just 10)))
  (should (equal (lg-preview lg-left-o (lg-left nil)) (lg-just nil)))
  (should (equal (lg-preview lg-left-o (lg-right 10)) lg-nothing))
  (should (equal (lg-review lg-left-o 7) (lg-left 7)))
  (should (equal (lg-over lg-left-o (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 3)))
  (should (equal (lg-over lg-left-o (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 2)))

  (should (equal (lg-preview lg-right-o (lg-right 10)) (lg-just 10)))
  (should (equal (lg-preview lg-right-o (lg-right nil)) (lg-just nil)))
  (should (equal (lg-preview lg-right-o (lg-left 10)) lg-nothing))
  (should (equal (lg-review lg-right-o 7) (lg-right 7)))
  (should (equal (lg-over lg-right-o (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 3)))
  (should (equal (lg-over lg-right-o (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 2))))

(ert-deftest lg-preview-disambiguates-present-nil ()
  (let* ((optic (lg-plist-key :name))
         (present-nil '(:name nil :age 10))
         (missing '(:age 10)))
    (should (equal (lg-preview optic present-nil) (lg-just nil)))
    (should (equal (lg-preview optic missing) lg-nothing))
    (should (lg-has optic present-nil))
    (should-not (lg-has optic missing))))

(ert-deftest lg-view-non-nil-signals ()
  (let ((optic (lg-plist-key :name)))
    (should-error (lg-view-non-nil optic '(:name nil)) :type 'lg-expected-non-nil)
    (should (equal (lg-view-non-nil optic '(:name "Ada")) "Ada"))))

(ert-deftest lg-alist-key ()
  (let ((optic (lg-alist-key "x" #'string=)))
    (should (equal (lg-preview optic '(("x" . nil) ("y" . 2))) (lg-just nil)))
    (should (equal (lg-over optic (lambda (_v) 9) '(("x" . nil) ("y" . 2)))
                   '(("x" . 9) ("y" . 2))))))

(ert-deftest lg-vector-and-string-traversals ()
  (should (equal (lg-over lg-vector (lambda (x) (+ x 1)) [1 2 3]) [2 3 4]))
  (should (equal (lg-over lg-string #'upcase "abc") "ABC"))
  (should (equal (lg-to-list-of lg-string "ab") '("a" "b"))))

(ert-deftest lg-indexed-vector-and-string-parity ()
  (should (equal (lg-ito-list-of lg-indexed-vector [10 20])
                 '((0 . 10) (1 . 20))))
  (should (equal (lg-iset lg-indexed-vector 0 [1 2 3]) [0 0 0]))
  (should (equal (lg-iover lg-indexed-vector (lambda (i x) (+ i x)) [10 10])
                 [10 11]))

  (should (equal (lg-ito-list-of lg-indexed-string "ab")
                 '((0 . "a") (1 . "b"))))
  (should (equal (lg-iover lg-indexed-string
                           (lambda (i ch)
                             (if (zerop i) (upcase ch) ch))
                           "ab")
                 "Ab")))

(ert-deftest lg-indexed-list-base-and-ops ()
  (let ((optic lg-indexed-list))
    (should (equal (lg-ito-list-of optic '(10 nil 30))
                   '((0 . 10) (1) (2 . 30))))
    (should (equal (lg-ipreview optic '(10 nil 30)) (lg-just '(0 . 10))))
    (should (equal (lg-ipreview optic '()) lg-nothing))
    (should (equal (lg-iover optic (lambda (i x) (if (= i 1) 99 x)) '(10 20 30))
                   '(10 99 30)))))

(ert-deftest lg-indexed-reindexing ()
  (let* ((base lg-indexed-list)
         (shifted (lg-ireindexed (lambda (index) (+ index 10)) base)))
    (should (equal (lg-ito-list-of shifted '(4 5)) '((10 . 4) (11 . 5))))
    (should (equal (lg-iover shifted (lambda (i x) (+ i x)) '(4 5)) '(14 16)))))

(ert-deftest lg-derived-getter-and-folds ()
  (let* ((getter (lg-getter #'length))
         (list-optic lg-list))
    (should (equal (lg-view getter '(a b c)) 3))
    (should (equal (lg-over getter (lambda (x) (+ x 1)) '(a b c)) '(a b c)))
    (should (= (lg-foldl-of list-optic #'+ 0 '(1 2 3 4)) 10))
    (should (= (lg-foldr-of list-optic (lambda (x acc) (+ x acc)) 0 '(1 2 3 4)) 10))
    (should (equal (lg-foldr-of list-optic (lambda (x acc) (cons x acc)) nil '(1 2 3))
                   '(1 2 3)))
    (should (= (lg-fold-map-of list-optic lg-monoid-sum #'identity '(1 2 3 4)) 10))
    (should (equal (lg-fold-map-of list-optic lg-monoid-string
                                   (lambda (x) (number-to-string x))
                                   '(1 2 3))
                   "123"))
    (should (= (lg-ifoldl-of lg-indexed-list
                             (lambda (acc i x) (+ acc (* i x)))
                             0
                             '(2 3 4))
               11))
    (should (= (lg-ifoldr-of lg-indexed-list
                             (lambda (i x acc) (+ acc (* i x)))
                             0
                             '(2 3 4))
               11))
    (should (= (lg-ifold-map-of lg-indexed-list lg-monoid-sum
                                (lambda (i x) (+ i x))
                                '(10 10))
               21))
    (should (lg-any-of list-optic (lambda (x) (= x 3)) '(1 2 3)))
    (should (lg-all-of list-optic (lambda (x) (> x 0)) '(1 2 3)))
    (should (= (lg-length-of list-optic '(1 2 3)) 3))
    (should (= (lg-sum-of list-optic '(1 2 3 4)) 10))
    (should (= (lg-product-of list-optic '(1 2 3 4)) 24))
    (should (= (lg-isum-of lg-indexed-list '(1 2 3 4)) 10))
    (should (= (lg-iproduct-of lg-indexed-list '(1 2 3 4)) 24))
    (should (equal (lg-maximum-of list-optic '(3 7 5)) (lg-just 7)))
    (should (equal (lg-minimum-of list-optic '(3 7 5)) (lg-just 3)))
    (should (equal (lg-maximum-of list-optic '()) lg-nothing))
    (should (equal (lg-minimum-of list-optic '()) lg-nothing))
    (should (equal (lg-imaximum-of lg-indexed-list '(3 7 5)) (lg-just '(1 . 7))))
    (should (equal (lg-iminimum-of lg-indexed-list '(3 7 5)) (lg-just '(0 . 3))))
    (should (equal (lg-imaximum-of lg-indexed-list '()) lg-nothing))
    (should (equal (lg-iminimum-of lg-indexed-list '()) lg-nothing))))

(ert-deftest lg-filtered-and-indexed-combinators ()
  (let* ((even (lg-filtered (lambda (x) (and (numberp x) (zerop (% x 2))))) )
         (filtered-indexed (lg-indexed-list-indices (lambda (i) (zerop (% i 2)))))
         (i-only (lg-indices (lambda (i) (eq i lg-no-index)))))
    (should (equal (lg-over even (lambda (x) (* x 10)) 2) 20))
    (should (equal (lg-over even (lambda (x) (* x 10)) 3) 3))
    (should (equal (lg-ito-list-of filtered-indexed '(10 11 12 13))
                   '((0 . 10) (2 . 12))))
    (should (equal (lg-iover filtered-indexed (lambda (_i x) (+ x 1)) '(10 11 12 13))
                   '(11 11 13 13)))
    (should (equal (lg-ito-list-of i-only 99) '((lg-no-index . 99))))))

(ert-deftest lg-indices-receive-enclosing-index ()
  (let ((even-indices (lg-compose-indexed lg-indexed-list
                                          (lg-indices #'cl-evenp))))
    (should (equal (lg-ito-list-of even-indices '(10 11 12 13))
                   '((0 . 10) (2 . 12))))
    (should (equal (lg-iset even-indices 'x '(10 11 12 13))
                   '(x 11 x 13)))
    (should (equal (lg-iover even-indices
                             (lambda (index focus) (+ index focus))
                             '(10 11 12 13))
                   '(10 11 14 13)))))

(ert-deftest lg-ifiltered-receives-enclosing-index ()
  (let ((seen nil))
    (lg-ito-list-of
     (lg-compose-indexed lg-indexed-list
                         (lg-ifiltered (lambda (index focus)
                                         (push (cons index focus) seen)
                                         nil)))
     '(10 11 12))
    (should (equal (nreverse seen) '((0 . 10) (1 . 11) (2 . 12)))))
  (should (equal (lg-iover (lg-compose-indexed
                            lg-indexed-list
                            (lg-ifiltered (lambda (index focus)
                                            (and (cl-evenp index)
                                                 (> focus 10)))))
                           (lambda (_index focus) (* 10 focus))
                           '(10 11 12 13))
                 '(10 11 120 13))))

(ert-deftest lg-as-indexed-inherits-enclosing-index ()
  (should (equal (lg-ito-list-of
                  (lg-compose-indexed lg-indexed-list (lg-as-indexed lg-list))
                  '((10 20) (30)))
                 '((0 . 10) (0 . 20) (1 . 30)))))

(ert-deftest lg-composition-operator-directions ()
  (let ((source '((1 . 2) . 3)))
    (should (= (lg-view (lg>> lg-car lg-cdr) source) 2))
    (should (= (lg-view (lg<< lg-cdr lg-car) source) 2))
    (should (equal (lg-set (lg>> lg-car lg-cdr) 9 source) '((1 . 9) . 3)))
    (should (equal (lg-view (lg>> lg-json-parse (lg-ix "name"))
                            "{\"name\":\"Ada\"}")
                   "Ada"))))

(ert-deftest lg-compose-rejects-wrong-optic-kind ()
  (should-error (lg-compose lg-car lg-indexed-list))
  (should-error (lg-compose lg-indexed-list))
  (should-error (lg-compose lg-car :oops))
  (should-error (lg-compose-indexed lg-indexed-list lg-car))
  (should-error (lg-compose-indexed 42))
  (should (equal (lg-view (lg-compose (lg-unindexed lg-indexed-list)) '(7)) 7))
  (should (equal (lg-ito-list-of (lg-compose-indexed (lg-as-indexed lg-car))
                                 '(7 . 8))
                 (list (cons lg-no-index 7)))))

(ert-deftest lg-icompose-with-combines-indices ()
  (should (equal (lg-ito-list-of
                  (lg-icompose-with #'cons lg-indexed-list lg-indexed-list)
                  '((10 20) (30)))
                 '(((0 . 0) . 10) ((0 . 1) . 20) ((1 . 0) . 30))))
  (should (equal (lg-iover (lg-icompose-with #'+ lg-indexed-list lg-indexed-list)
                           (lambda (index focus) (+ (* 100 index) focus))
                           '((1 2) (3)))
                 '((1 102) (103)))))

(ert-deftest lg-either-prisms-reject-non-either-values ()
  (should (equal (lg-preview lg-left-o 5) lg-nothing))
  (should (equal (lg-preview lg-right-o "hi") lg-nothing))
  (should (equal (lg-over lg-right-o #'1+ 5) 5))
  (should-not (lg-left-p 5))
  (should-not (lg-right-p "hi")))

(ert-deftest lg-review-propagates-builder-errors ()
  ;; A builder's own validation error must not be masked as a
  ;; capability error.
  (let ((err (should-error (lg-review lg-number-string "not-a-number"))))
    (should-not (eq (car err) 'lg-unsupported-capability)))
  ;; A genuine capability gap signals `lg-unsupported-capability'.
  (should-error (lg-review lg-list '(1 2 3))
                :type 'lg-unsupported-capability)
  (should-error (lg-view (lg-re lg-list) 5)
                :type 'lg-unsupported-capability))

(ert-deftest lg-clone-functions-preserve-behavior ()
  (let ((iso (lg-clone-iso lg-list->vector)))
    (should (equal (lg-view iso '(1 2)) [1 2]))
    (should (equal (lg-review iso [1 2]) '(1 2))))
  (let ((lens (lg-clone-lens lg-car)))
    (should (= (lg-view lens '(1 . 2)) 1))
    (should (equal (lg-set lens 9 '(1 . 2)) '(9 . 2))))
  (let ((prism (lg-clone-prism lg-number-string)))
    (should (equal (lg-preview prism "42") (lg-just 42)))
    (should (equal (lg-preview prism "x") lg-nothing))
    (should (equal (lg-review prism 42) "42")))
  (let ((affine (lg-clone-affine (lg-plist-key :name))))
    (should (equal (lg-preview affine '(:name "Ada")) (lg-just "Ada")))
    (should (equal (lg-set affine "Grace" '(:name "Ada")) '(:name "Grace")))
    (should (equal (lg-set affine "X" '(:other 1)) '(:other 1))))
  (let ((affine (lg-clone-affine (lg-compose lg-car lg-non-nil))))
    (should (equal (lg-preview affine '(1 . 2)) (lg-just 1)))
    (should (equal (lg-preview affine '(nil . 2)) lg-nothing))
    (should (equal (lg-set affine 9 '(1 . 2)) '(9 . 2))))
  (let ((traversal (lg-clone-traversal lg-list)))
    (should (equal (lg-over traversal #'1+ '(1 2 3)) '(2 3 4))))
  (let ((review (lg-clone-review lg-number-string)))
    (should (equal (lg-review review 42) "42"))))

(ert-deftest lg-keyed-optics-reject-non-keyed-lists ()
  (should-error (lg-preview (lg-ix :k) '(1 2 3)))
  (should-error (lg-set (lg-ix :k) 9 '(1 2 3)))
  (should-error (lg-set (lg-at :k) (lg-just 1) '(1 2 3))))

(ert-deftest lg-at-deletion-removes-duplicate-keys ()
  (should (equal (lg-set (lg-at :k) lg-nothing '(:k 1 :k 2 :other 3))
                 '(:other 3)))
  (should (equal (lg-preview (lg-ix :k)
                             (lg-set (lg-at :k) lg-nothing
                                     '(:k 1 :k 2 :other 3)))
                 lg-nothing))
  (should (equal (lg-set (lg-at 'a) lg-nothing '((a . 1) (b . 2) (a . 3)))
                 '((b . 2)))))

(ert-deftest lg-just-o-matches-library-maybe ()
  (should (equal (lg-preview lg-just-o (lg-just 5)) (lg-just 5)))
  (should (equal (lg-preview lg-just-o lg-nothing) lg-nothing))
  (should (equal (lg-preview lg-just-o 5) lg-nothing))
  (should (equal (lg-review lg-just-o 5) (lg-just 5))))

(ert-deftest lg-slice-supports-vectors-and-strings ()
  (should (equal (lg-view (lg-slice 1 3) [1 2 3 4]) [2 3]))
  (should (equal (lg-set (lg-slice 1 1) [9] [1 2]) [1 9 2]))
  (should (equal (lg-over (lg-slice 0 2) #'upcase "abcd") "ABcd"))
  (should (equal (lg-set (lg-slice 2 2) "--" "abcd") "ab--cd"))
  (should-error (lg-view (lg-slice 0 9) [1 2]))
  (should-error (lg-set (lg-slice 0 1) '(1) [1 2])))

(ert-deftest lg-read-paths-handle-large-containers ()
  (let ((big (make-list 10000 1)))
    (should (= (length (lg-to-list-of lg-list big)) 10000))
    (should (equal (lg-preview lg-list big) (lg-just 1)))
    (should (= (length (lg-ito-list-of lg-indexed-list big)) 10000))
    (should (= (lg-length-of lg-list big) 10000))
    (should (equal (lg-over lg-list #'identity big) big))))

(ert-deftest lg-at-rejects-raw-values ()
  (should-error (lg-set (lg-at :k) 5 '(:k 1 :other 2)))
  (should-error (lg-set (lg-at 'k) 5 '((k . 1))))
  (let ((table (make-hash-table :test 'equal)))
    (puthash "k" 1 table)
    (should-error (lg-set (lg-at "k") 5 table))
    (should (= (gethash "k" table) 1)))
  (should-error (lg-set (lg-at :k) (lg-just 1) 42)))

(ert-deftest lg-clone-affine-rejects-multi-focus ()
  (let ((clone (lg-clone-affine lg-list)))
    (should-error (lg-over clone #'identity '(1 2 3)))
    (should-error (lg-preview clone '(1 2 3)))
    (should (equal (lg-preview clone '(1)) (lg-just 1)))
    (should (equal (lg-set clone 9 '(1)) '(9)))
    (should (equal (lg-preview clone '()) lg-nothing))))

(ert-deftest lg-json-parse-with-rejects-colliding-sentinels ()
  (should-error (lg-json-parse-with 'hash-table 'array nil 0))
  (should-error (lg-json-parse-with 'hash-table 'array nil "no"))
  (should-error (lg-json-parse-with 'hash-table 'array nil t))
  (should-error (lg-json-parse-with 'hash-table 'array 0 lg-false))
  (should-error (lg-json-parse-with 'hash-table 'array :x :x))
  (should-error (lg-json-parse-with 'hash-table 'array lg-true lg-false))
  (should (lg-optic-p (lg-json-parse-with 'hash-table 'array :null :false))))

(ert-deftest lg-package-loads-without-native-json ()
  ;; Construction defers the availability check to first use, so the
  ;; defconst `lg-json-parse' must not require native JSON.
  (cl-letf (((symbol-function 'json-available-p) (lambda () nil)))
    (should (lg-optic-p (lg-json-parse-with 'hash-table 'array nil lg-false)))
    (should-error (lg-view lg-json-parse "{}"))))

(ert-deftest lg-kind-pinned-key-optics ()
  ;; lg-plist-key/lg-alist-key fix the container kind instead of
  ;; inferring it from shape.
  (should (equal (lg-preview (lg-plist-key 'a) '((a . 1) (b . 2)))
                 lg-nothing))
  (should (equal (lg-preview (lg-alist-key :k) '(:k 1)) lg-nothing))
  (should (equal (lg-preview (lg-plist-key :k) '(:k 1)) (lg-just 1)))
  (should (equal (lg-set (lg-alist-key 'a) 9 '((a . 1) (b . 2)))
                 '((a . 9) (b . 2))))
  ;; Kind-pinned at-lenses: insertion into nil respects the pinned kind.
  (should (equal (lg-set (lg-plist-at :k) (lg-just 1) nil) '(:k 1)))
  (should (equal (lg-set (lg-alist-at :k) (lg-just 1) nil) '((:k . 1))))
  (should (equal (lg-set (lg-plist-at :k) lg-nothing '(:k 1 :o 2)) '(:o 2)))
  (should-error (lg-set (lg-plist-at :k) 5 '(:k 1))))

(ert-deftest lg-unsupported-containers-signal-descriptive-errors ()
  (should-error (lg-view (lg-nth 0) 42))
  (should-error (lg-view (lg-slice 0 1) 42))
  (should-error (lg-view (lg-slice 0 1) (bool-vector t nil)))
  (should-error (lg-preview (lg-ix :k) 42))
  (should-error (lg-set (lg-at :k) (lg-just 1) "string")))

(ert-deftest lg-monoid-any-all-product ()
  (should (eq (lg-fold-map-of lg-list lg-monoid-any #'cl-evenp '(1 3 4)) t))
  (should (eq (lg-fold-map-of lg-list lg-monoid-any #'cl-evenp '(1 3 5)) nil))
  (should (eq (lg-fold-map-of lg-list lg-monoid-all #'cl-evenp '(2 4)) t))
  (should (eq (lg-fold-map-of lg-list lg-monoid-all #'cl-evenp '(2 3)) nil))
  (should (= (lg-fold-map-of lg-list lg-monoid-product #'identity '(2 3 4)) 24))
  (should (= (lg-fold-map-of lg-list lg-monoid-product #'identity '()) 1)))

(ert-deftest lg-non-nil-helpers-and-macros ()
  (let* ((optic (lg-required (lg-plist-key :name)))
         (pair-optic (lg-compose lg-car lg-cdr)))
    (should (equal (lg-preview-or "unknown" optic '(:name "Ada")) "Ada"))
    (should (equal (lg-preview-or "unknown" optic '(:name nil)) "unknown"))
    (should (equal (lg-over lg-cdr
                            (lambda (x) (* x 2))
                            (lg-over lg-car
                                     (lambda (x) (+ x 10))
                                     '(1 . 2)))
                   '(11 . 4)))
    (should (equal (lg-set lg-cdr
                           9
                           (lg-set lg-car
                                   7
                                   '(1 . 2)))
                   '(7 . 9)))
    (should (equal (lg-view pair-optic '((1 . 2) . 3)) 2))))

(ert-deftest lg-extension-point-custom-affine-optic ()
  (let ((optic
         (lg-affine
          (lambda (source)
            (if (numberp source) (lg-just source) lg-nothing))
          (lambda (_source new-focus)
            (* 2 new-focus)))))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 10) 22))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 'nope) 'nope))
    (should (equal (lg-preview optic 10) (lg-just 10)))
    (should (equal (lg-preview optic 'nope) lg-nothing))))

(ert-deftest lg-ix-and-at-for-keyed-structures ()
  (let* ((plist '(:name nil :age 10))
         (alist '(("name" . nil) ("age" . 10)))
         (table (let ((h (make-hash-table :test 'equal)))
                  (puthash "name" nil h)
                  (puthash "age" 10 h)
                  h)))
    (should (equal (lg-preview (lg-ix :name) plist) (lg-just nil)))
    (should (equal (lg-preview (lg-ix :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-ix :name) "Ada" plist) '(:name "Ada" :age 10)))
    (should (equal (lg-set (lg-ix :missing) 1 plist) plist))

    (should (equal (lg-view (lg-at :name) plist) (lg-just nil)))
    (should (equal (lg-view (lg-at :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-at :missing) (lg-just 99) plist)
                   '(:name nil :age 10 :missing 99)))
    (should (equal (lg-set (lg-at :age) lg-nothing plist)
                   '(:name nil)))

    (should (equal (lg-preview (lg-ix "name" #'string=) alist) (lg-just nil)))
    (should (equal (lg-set (lg-at "missing" #'string=) (lg-just 7) alist)
                   '(("name") ("age" . 10) ("missing" . 7))))
    (should (equal (lg-set (lg-at "age" #'string=) lg-nothing alist)
                   '(("name"))))

    (should (equal (lg-preview (lg-ix "name") table) (lg-just nil)))
    (let ((updated (lg-set (lg-at "name") (lg-just "Ada") table)))
      (should (equal (gethash "name" updated) "Ada"))
      (should (= (hash-table-count updated) 2)))
    (let ((removed (lg-set (lg-at "age") lg-nothing table)))
      (should-not (gethash "age" removed))
      (should (= (hash-table-count removed) 1)))))

(ert-deftest lg-unmaybe-lossy-adapter-over-at ()
  (let* ((profile '(:name nil :age 10))
         (age-optic (lg-compose (lg-at :age) lg-unmaybe))
         (name-optic (lg-compose (lg-at :name) lg-unmaybe)))
    (should (equal (lg-view age-optic profile) 10))
    (should (equal (lg-view name-optic profile) nil))
    (should (equal (lg-set age-optic nil profile) '(:name nil)))
    (should (equal (lg-set age-optic 42 profile) '(:name nil :age 42)))))

(ert-deftest lg-fold-review-and-indexed-combinators ()
  (let* ((tr lg-list)
         (itr lg-indexed-list)
         (reviewer (lg-unto (lambda (x) (list :wrapped x)))))
    (should (equal (lg-preview tr '(4 5 6)) (lg-just 4)))
    (should (equal (lg-last-of tr '(4 5 6)) (lg-just 6)))
    (should (equal (lg-find-of tr (lambda (x) (> x 4)) '(1 3 5 7)) (lg-just 5)))
    (should (lg-none-of tr (lambda (x) (eq 1 (% x 2))) '(2 4 6)))
    (should (equal (lg-ipreview itr '(10 11)) (lg-just '(0 . 10))))
    (should (equal (lg-ilast-of itr '(10 11)) (lg-just '(1 . 11))))
    (should (equal (lg-ifind-of itr (lambda (i _x) (= i 1)) '(10 11 12)) (lg-just '(1 . 11))))
    (should (equal (lg-iover itr (lambda (i x) (+ i x)) '(10 11)) '(10 12)))
    (should (lg-iany-of itr (lambda (i x) (= (+ i x) 12)) '(10 11)))
    (should (lg-inone-of itr (lambda (_i x) (< x 0)) '(1 2 3)))
    (should (lg-iall-of itr (lambda (i x) (>= (+ i x) 1)) '(1 2 3)))
    (should (= (lg-ilength-of itr '(1 2 3 4)) 4))
    (should (equal (lg-review reviewer 9) '(:wrapped 9)))
    (should (equal (lg-reviews reviewer #'car 9) :wrapped))))

(ert-deftest lg-indexed-helper-parity ()
  (let ((optic lg-indexed-list)
        (values '(nil 10 20)))
    (should (equal (lg-ipreview-or '(missing . missing) optic values)
                   '(0)))
    (should (equal (lg-ipreview-or '(missing . missing) optic '())
                   '(missing . missing)))
    (should (equal (lg-iview optic '(10 20)) '(0 . 10)))
    (should-error (lg-iview optic '()) :type 'lg-no-focus)
    (should (equal (lg-iview-non-nil optic '(10 20)) '(0 . 10)))
    (should-error (lg-iview-non-nil optic '(nil 20)) :type 'lg-expected-non-nil)
    (should (lg-ihas optic '(10)))
    (should-not (lg-ihas optic '()))
    (should (equal (lg-iover optic (lambda (i x) (+ i x)) '(10 10))
                   '(10 11)))))

(ert-deftest lg-indexed-unindexed-bridges ()
  (let ((plain lg-list)
        (indexed lg-indexed-list))
    (should (equal (lg-ito-list-of (lg-as-indexed plain) '(4 5))
                   '((lg-no-index . 4) (lg-no-index . 5))))
    (should (equal (lg-over (lg-unindexed indexed) (lambda (x) (+ x 1)) '(4 5))
                   '(5 6)))))

(ert-deftest lg-randomized-core-laws ()
  (let ((lens lg-car)
        (prism lg-non-nil)
        (traversal lg-list))
    (dotimes (_ 100)
      (let* ((pair (cons (lg-test--random-int) (lg-test--random-int)))
             (v1 (lg-test--random-int))
             (v2 (lg-test--random-int)))
        (should (equal (lg-set lens (lg-view lens pair) pair) pair))
        (should (equal (lg-view lens (lg-set lens v1 pair)) v1))
        (should (equal (lg-set lens v2 (lg-set lens v1 pair))
                       (lg-set lens v2 pair)))))

    (dotimes (_ 100)
      (let ((value (if (zerop (random 4)) nil (lg-test--random-int))))
        (should (equal (lg-preview prism (lg-review prism value))
                       (if value (lg-just value) lg-nothing)))
        (let ((previewed (lg-preview prism value)))
          (when (lg-just-p previewed)
            (should (equal (lg-review prism (cdr previewed)) value))))))

    (dotimes (_ 100)
      (let* ((xs (lg-test--random-list))
             (f (lambda (x) (+ x 1)))
             (g (lambda (x) (* x 2))))
        (should (equal (lg-over traversal #'identity xs) xs))
        (should (equal (lg-over traversal (lambda (x) (funcall g (funcall f x))) xs)
                       (lg-over traversal g (lg-over traversal f xs))))))))

(ert-deftest lg-randomized-keyed-optics-laws ()
  (dolist (kind '(plist alist hash))
    (dotimes (_ 100)
      (let* ((present (zerop (random 2)))
             (value (if (zerop (random 4)) nil (lg-test--random-int)))
             (replacement (if (zerop (random 4)) nil (lg-test--random-int)))
             (key (if (eq kind 'plist) :k "k"))
             (testfn (if (eq kind 'alist) #'string= nil))
             (source
              (pcase kind
                ('plist (if present
                            (list :k value :other 1)
                          (list :other 1)))
                ('alist (if present
                            (list (cons "k" value) (cons "other" 1))
                          (list (cons "other" 1))))
                ('hash (let ((table (make-hash-table :test 'equal)))
                         (when present
                           (puthash "k" value table))
                         (puthash "other" 1 table)
                         table))))
             (ix (lg-ix key testfn))
             (at (lg-at key testfn)))
        (should (equal (lg-has ix source) present))
        (should (equal (lg-view at source)
                       (if present (lg-just value) lg-nothing)))

        (let ((ix-updated (lg-set ix replacement source)))
          (should (equal (lg-preview ix ix-updated)
                         (if present (lg-just replacement) lg-nothing))))

        (let ((at-updated (lg-set at (lg-just replacement) source)))
          (should (equal (lg-preview ix at-updated)
                         (lg-just replacement))))

        (let ((at-removed (lg-set at lg-nothing source)))
          (should (equal (lg-preview ix at-removed) lg-nothing)))))))

(ert-deftest lg-randomized-vector-and-string-traversal-laws ()
  (let ((vector-optic lg-vector)
        (string-optic lg-string))
    (dotimes (_ 100)
      (let* ((xs (lg-test--random-list))
             (vec (vconcat xs))
             (f (lambda (x) (+ x 1)))
             (g (lambda (x) (* x 2))))
        (should (equal (lg-over vector-optic #'identity vec) vec))
        (should (equal (lg-over vector-optic (lambda (x) (funcall g (funcall f x))) vec)
                       (lg-over vector-optic g (lg-over vector-optic f vec))))))

    (dotimes (_ 100)
      (let ((s (lg-test--random-string)))
        (should (equal (lg-over string-optic #'identity s) s))
        (should (equal (lg-over string-optic #'upcase s)
                       (upcase s)))))))

(ert-deftest lg-nth-supports-lists-vectors-and-strings ()
  (let ((optic (lg-nth 1)))
    (should (equal (lg-view optic '(4 5 6)) 5))
    (should (equal (lg-set optic 9 '(4 5 6)) '(4 9 6)))
    (should (equal (lg-view optic [4 5 6]) 5))
    (should (equal (lg-set optic 9 [4 5 6]) [4 9 6]))
    (should (equal (lg-view optic "abcd") ?b))
    (should (equal (lg-set optic ?Z "abcd") "aZcd"))
    (should-error (lg-set optic "Z" "abcd"))
    (let ((bits (make-bool-vector 3 nil)))
      (aset bits 0 t)
      (aset bits 2 t)
      (should (equal (lg-view optic bits) nil))
      (let ((updated (lg-set optic t bits)))
        (should (equal (aref updated 0) t))
        (should (equal (aref updated 1) t))
    (should (equal (aref updated 2) t))))
    (should-error (lg-view optic 'foo))
    (should-error (lg-view (lg-nth 9) [1 2]))))

(ert-deftest lg-slice-supports-list-insert-and-replace ()
  (should (equal (lg-view (lg-slice 1 2) '(1 2 3)) '(2)))
  (should (equal (lg-set (lg-slice 1 1) '(4) '(1 2 3)) '(1 4 2 3)))
  (should (equal (lg-set (lg-slice 0 0) '(5) '(1 2 3)) '(5 1 2 3)))
  (should (equal (lg-set (lg-slice 3 3) '(4 4) '(1 2 3)) '(1 2 3 4 4)))
  (should (equal (lg-set (lg-slice 1 3) '(8 9) '(1 2 3 4)) '(1 8 9 4)))
  (should-error (lg-view (lg-slice -1 2) '(1 2 3)))
  (should-error (lg-view (lg-slice 2 1) '(1 2 3)))
  (should-error (lg-set (lg-slice 1 1) 9 '(1 2 3))))

(ert-deftest lg-json-parse-default-prism-roundtrip-and-edit ()
  (let ((json "{\"name\":\"Ada\",\"tags\":[\"elisp\",\"optics\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (should (equal
             (lg-over (lg-compose lg-json-parse (lg-ix "name")) #'upcase json)
             "{\"name\":\"ADA\",\"tags\":[\"elisp\",\"optics\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (should (equal
             (lg-over (lg-compose lg-json-parse (lg-ix "tags"))
                      (lambda (tags)
                        (let ((copy (copy-sequence tags)))
                          (aset copy 1 (upcase (aref copy 1)))
                          copy))
                      json)
             "{\"name\":\"Ada\",\"tags\":[\"elisp\",\"OPTICS\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (let ((parsed (lg-view lg-json-parse json)))
      (should (eq (gethash "active" parsed) lg-true))
       (should (eq (gethash "disabled" parsed) lg-false))
       (should (null (gethash "note" parsed))))))

(ert-deftest lg-json-parse-custom-with-args ()
  (let* ((prism (lg-json-parse-with 'alist 'array :null lg-false))
         (json "{\"ok\":true,\"nope\":false,\"items\":[1,2]}")
         (value (lg-view prism json)))
    (should (equal value '((ok . lg-true) (nope . lg-false) (items . [1 2]))))
    (should (equal (lg-review prism value) json))))

(ert-deftest lg-json-parse-with-rejects-ambiguous-types ()
  (should-error (lg-json-parse-with 'alist 'list :null lg-false))
  (should-error (lg-json-parse-with 'plist 'list :null lg-false))
  (should-error (lg-json-parse-with 'alist 'array nil lg-false))
  (should-error (lg-json-parse-with 'plist 'array nil lg-false))
  (should-error (lg-json-parse-with 'hash-table 'list nil lg-false))
  (should-error (lg-json-parse-with 'vector 'array nil lg-false)))

(ert-deftest lg-json-parse-with-identity-roundtrips ()
  (dolist (combo '((hash-table array nil)
                   (hash-table list :null)
                   (alist array :null)
                   (plist array :null)))
    (let ((prism (apply #'lg-json-parse-with (append combo (list lg-false)))))
      (dolist (json '("[true,false]" "{}" "[]" "null"
                      "[[1,2],[3,4]]" "[\"a\",1]"
                      "{\"a\":null,\"b\":false,\"c\":{},\"d\":[]}"))
        (should (equal (lg-over prism #'identity json) json))))))

(ert-deftest lg-json-parse-with-tags-booleans-in-containers ()
  (should (equal (lg-view (lg-json-parse-with 'plist 'array :null lg-false)
                          "{\"a\":true,\"b\":[false,null]}")
                 '(:a lg-true :b [lg-false :null])))
  (should (equal (lg-view (lg-json-parse-with 'hash-table 'list :null lg-false)
                          "[true,false]")
                 '(lg-true lg-false))))

(ert-deftest lg-json-parse-prism-fails-gracefully ()
  (let ((bad "{\"missing\":true")
        (optic (lg-json-parse-with 'hash-table 'array nil lg-false)))
    (should (equal (lg-preview optic bad) lg-nothing))
    (should-error (lg-view optic bad))
    (should (equal (lg-over optic #'identity bad) bad))))

(provide 'looking-glass-core-test)

;;; looking-glass-core-test.el ends here
