;;; looking-glass-test.el --- Tests for looking-glass -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'looking-glass)
(require 'looking-glass-convert)

(defun lg-test--random-int ()
  "Return a random integer in a small range for repeatable law tests."
  (- (random 200) 100))

(defun lg-test--random-list ()
  "Return a random list of integers."
  (let ((length (random 8))
        (result nil))
    (dotimes (_ length (nreverse result))
      (push (lg-test--random-int) result))))

(ert-deftest lg-lens-view-set-over ()
  (let ((optic (lg-car)))
    (should (equal (lg-view optic '(1 . 2)) 1))
    (should (equal (lg-set optic 9 '(1 . 2)) '(9 . 2)))
    (should (equal (lg-over optic (lambda (x) (+ x 3)) '(1 . 2)) '(4 . 2)))))

(ert-deftest lg-compose-nested-pairs ()
  (let* ((nested '((1 . 2) . 3))
         (optic (lg-compose (lg-cdr) (lg-car))))
    (should (equal (lg-view optic nested) 2))
    (should (equal (lg-set optic 7 nested) '((1 . 7) . 3)))))

(ert-deftest lg-traversal-list-over-and-fold ()
  (let ((optic (lg-list)))
    (should (equal (lg-over optic (lambda (x) (* x 10)) '(1 2 3)) '(10 20 30)))
    (should (equal (lg-to-list-of optic '(1 2 3)) '(1 2 3)))))

(ert-deftest lg-prism-non-nil ()
  (let ((optic (lg-non-nil)))
    (should (equal (lg-preview optic 42) 42))
    (should (equal (lg-review optic 42) 42))
    (should (equal (lg-preview-result optic nil) lg-nothing))
    (should-not (lg-has optic nil))))

(ert-deftest lg-review-support ()
  (let* ((just (lg-just-o))
         (iso (lg-iso #'number-to-string #'string-to-number))
         (composed (lg-compose just iso)))
    (should (equal (lg-review just 7) '(just . 7)))
    (should (equal (lg-review iso "42") 42))
    (should (equal (lg-review composed "9") '(just . 9)))
    (should-error (lg-review (lg-list) 1))))

(ert-deftest lg-either-core-and-prisms ()
  (should (lg-either-p (lg-left 1)))
  (should (lg-either-p (lg-right nil)))
  (should-not (lg-either-p 42))
  (should (= (lg-either-value (lg-left 5)) 5))

  (should (equal (lg-preview (lg-left-o) (lg-left 10)) 10))
  (should (equal (lg-preview-result (lg-left-o) (lg-left nil)) (lg-just nil)))
  (should (equal (lg-preview (lg-left-o) (lg-right 10)) nil))
  (should (equal (lg-review (lg-left-o) 7) (lg-left 7)))
  (should (equal (lg-over (lg-left-o) (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 3)))
  (should (equal (lg-over (lg-left-o) (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 2)))

  (should (equal (lg-preview (lg-right-o) (lg-right 10)) 10))
  (should (equal (lg-preview-result (lg-right-o) (lg-right nil)) (lg-just nil)))
  (should (equal (lg-preview (lg-right-o) (lg-left 10)) nil))
  (should (equal (lg-review (lg-right-o) 7) (lg-right 7)))
  (should (equal (lg-over (lg-right-o) (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 3)))
  (should (equal (lg-over (lg-right-o) (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 2))))

(ert-deftest lg-convert-list-vector-iso ()
  (let ((optic (lg-list-vector-iso)))
    (should (equal (lg-view optic '(1 2 3)) [1 2 3]))
    (should (equal (lg-review optic [1 2 3]) '(1 2 3)))
    (should (equal (lg-over optic (lambda (v) (vconcat v [4])) '(1 2 3)) '(1 2 3 4)))))

(ert-deftest lg-convert-number-string-prism ()
  (let ((optic (lg-number-string-prism)))
    (should (equal (lg-preview optic "42") 42))
    (should (equal (lg-preview optic "  -3.5 ") -3.5))
    (should-not (lg-has optic "42x"))
    (should (equal (lg-review optic 15) "15"))))

(ert-deftest lg-convert-char-string-prism ()
  (let ((optic (lg-char-string-prism)))
    (should (equal (lg-preview optic "A") ?A))
    (should-not (lg-has optic "AB"))
    (should (equal (lg-review optic ?Z) "Z"))))

(ert-deftest lg-convert-symbol-string-prism ()
  (let* ((existing (intern "lg-symbol-string-prism-test"))
         (missing-name (format "lg-missing-%s" (float-time)))
         (optic (lg-symbol-string-prism)))
    (should (equal (lg-preview optic "lg-symbol-string-prism-test") existing))
    (should-not (lg-has optic missing-name))
    (should (equal (lg-review optic 'hello) "hello"))))

(ert-deftest lg-convert-alist-plist-prism ()
  (let ((optic (lg-alist-plist-prism)))
    (should (equal (lg-preview optic '((:a . 1) (:b . nil))) '(:a 1 :b nil)))
    (should (equal (lg-review optic '(:a 1 :b nil)) '((:a . 1) (:b))))
    (should-not (lg-has optic '((:a . 1) (:a . 2))))
    (should-error (lg-review optic '(:a 1 :a 2)))))

(ert-deftest lg-preview-result-disambiguates-present-nil ()
  (let* ((optic (lg-plist-key :name))
         (present-nil '(:name nil :age 10))
         (missing '(:age 10)))
    (should (equal (lg-preview-result optic present-nil) (lg-just nil)))
    (should (equal (lg-preview-result optic missing) lg-nothing))
    (should (lg-has optic present-nil))
    (should-not (lg-has optic missing))))

(ert-deftest lg-view-non-nil-signals ()
  (let ((optic (lg-plist-key :name)))
    (should-error (lg-view-non-nil optic '(:name nil)) :type 'lg-expected-non-nil)
    (should (equal (lg-view-non-nil optic '(:name "Ada")) "Ada"))))

(ert-deftest lg-alist-key ()
  (let ((optic (lg-alist-key "x" #'string=)))
    (should (equal (lg-preview-result optic '(("x" . nil) ("y" . 2))) (lg-just nil)))
    (should (equal (lg-over optic (lambda (_v) 9) '(("x" . nil) ("y" . 2)))
                   '(("x" . 9) ("y" . 2))))))

(ert-deftest lg-vector-and-string-traversals ()
  (should (equal (lg-over (lg-vector) (lambda (x) (+ x 1)) [1 2 3]) [2 3 4]))
  (should (equal (lg-over (lg-string) #'upcase "abc") "ABC"))
  (should (equal (lg-to-list-of (lg-string) "ab") '("a" "b"))))

(ert-deftest lg-indexed-list-base-and-ops ()
  (let ((optic (lg-indexed-list)))
    (should (equal (lg-ito-list-of optic '(10 nil 30))
                   '((0 . 10) (1) (2 . 30))))
    (should (equal (lg-ipreview-result optic '(10 nil 30)) (lg-just '(0 . 10))))
    (should (equal (lg-ipreview-result optic '()) lg-nothing))
    (should (equal (lg-iover optic (lambda (i x) (if (= i 1) 99 x)) '(10 20 30))
                   '(10 99 30)))))

(ert-deftest lg-indexed-reindexing ()
  (let* ((base (lg-indexed-list))
         (shifted (lg-ireindexed (lambda (index) (+ index 10)) base)))
    (should (equal (lg-ito-list-of shifted '(4 5)) '((10 . 4) (11 . 5))))
    (should (equal (lg-iover shifted (lambda (i x) (+ i x)) '(4 5)) '(14 16)))))

(ert-deftest lg-derived-getter-and-folds ()
  (let* ((getter (lg-getter #'length))
         (list-optic (lg-list)))
    (should (equal (lg-view getter '(a b c)) 3))
    (should (equal (lg-over getter (lambda (x) (+ x 1)) '(a b c)) '(a b c)))
    (should (= (lg-foldl-of list-optic #'+ 0 '(1 2 3 4)) 10))
    (should (= (lg-ifoldl-of (lg-indexed-list)
                             (lambda (acc i x) (+ acc (* i x)))
                             0
                             '(2 3 4))
               11))
    (should (lg-any-of list-optic (lambda (x) (= x 3)) '(1 2 3)))
    (should (lg-all-of list-optic (lambda (x) (> x 0)) '(1 2 3)))
    (should (= (lg-count-of list-optic '(1 2 3)) 3))))

(ert-deftest lg-filtered-and-indexed-combinators ()
  (let* ((even (lg-filtered (lambda (x) (and (numberp x) (zerop (% x 2))))) )
         (filtered-indexed (lg-indexed-list-indices (lambda (i) (zerop (% i 2)))))
         (i-only (lg-indices (lambda (i) (eq i nil)))))
    (should (equal (lg-over even (lambda (x) (* x 10)) 2) 20))
    (should (equal (lg-over even (lambda (x) (* x 10)) 3) 3))
    (should (equal (lg-ito-list-of filtered-indexed '(10 11 12 13))
                   '((0 . 10) (2 . 12))))
    (should (equal (lg-iover filtered-indexed (lambda (_i x) (+ x 1)) '(10 11 12 13))
                   '(11 11 13 13)))
    (should (equal (lg-ito-list-of i-only 99) '((nil . 99))))))

(ert-deftest lg-non-nil-helpers-and-macros ()
  (let* ((optic (lg-required (lg-plist-key :name)))
         (pair-optic (lg-optic (lg-cdr) (lg-car))))
    (should (equal (lg-preview-or "unknown" optic '(:name "Ada")) "Ada"))
    (should (equal (lg-preview-or "unknown" optic '(:name nil)) "unknown"))
    (should (equal (lg-over (lg-cdr)
                            (lambda (x) (* x 2))
                            (lg-over (lg-car)
                                     (lambda (x) (+ x 10))
                                     '(1 . 2)))
                   '(11 . 4)))
    (should (equal (lg-set (lg-cdr)
                           9
                           (lg-set (lg-car)
                                   7
                                   '(1 . 2)))
                   '(7 . 9)))
    (should (equal (lg-view pair-optic '((1 . 2) . 3)) 2))))

(ert-deftest lg-extension-point-custom-affine-optic ()
  (let ((optic
         (lg-affine
           (lambda (source)
             (if (numberp source) (lg-just source) lg-nothing))
           (lambda (_source new-focus)
             (* 2 new-focus)))))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 10) 22))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 'nope) 'nope))
    (should (equal (lg-preview-result optic 10) (lg-just 10)))
    (should (equal (lg-preview-result optic 'nope) lg-nothing))))

(ert-deftest lg-ix-and-at-for-keyed-structures ()
  (let* ((plist '(:name nil :age 10))
         (alist '(("name" . nil) ("age" . 10)))
         (table (let ((h (make-hash-table :test 'equal)))
                  (puthash "name" nil h)
                  (puthash "age" 10 h)
                  h)))
    (should (equal (lg-preview-result (lg-ix :name) plist) (lg-just nil)))
    (should (equal (lg-preview-result (lg-ix :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-ix :name) "Ada" plist) '(:name "Ada" :age 10)))
    (should (equal (lg-set (lg-ix :missing) 1 plist) plist))

    (should (equal (lg-view (lg-at :name) plist) (lg-just nil)))
    (should (equal (lg-view (lg-at :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-at :missing) (lg-just 99) plist)
                   '(:name nil :age 10 :missing 99)))
    (should (equal (lg-set (lg-at :age) lg-nothing plist)
                   '(:name nil)))

    (should (equal (lg-preview-result (lg-ix "name" #'string=) alist) (lg-just nil)))
    (should (equal (lg-set (lg-at "missing" #'string=) (lg-just 7) alist)
                   '(("name") ("age" . 10) ("missing" . 7))))
    (should (equal (lg-set (lg-at "age" #'string=) lg-nothing alist)
                   '(("name"))))

    (should (equal (lg-preview-result (lg-ix "name") table) (lg-just nil)))
    (let ((updated (lg-set (lg-at "name") (lg-just "Ada") table)))
      (should (equal (gethash "name" updated) "Ada"))
      (should (= (hash-table-count updated) 2)))
    (let ((removed (lg-set (lg-at "age") lg-nothing table)))
      (should-not (gethash "age" removed))
      (should (= (hash-table-count removed) 1)))))

(ert-deftest lg-fold-review-and-indexed-combinators ()
  (let* ((tr (lg-list))
         (itr (lg-indexed-list))
         (reviewer (lg-unto (lambda (x) (list :wrapped x)))))
    (should (equal (lg-first-of tr '(4 5 6)) 4))
    (should (equal (lg-last-of tr '(4 5 6)) 6))
    (should (equal (lg-find-of tr (lambda (x) (> x 4)) '(1 3 5 7)) 5))
    (should (lg-none-of tr (lambda (x) (eq 1 (% x 2))) '(2 4 6)))
    (should (equal (lg-ifirst-of itr '(10 11)) '(0 . 10)))
    (should (equal (lg-ilast-of itr '(10 11)) '(1 . 11)))
    (should (equal (lg-ifind-of itr (lambda (i _x) (= i 1)) '(10 11 12)) '(1 . 11)))
    (should (equal (lg-imap-of itr (lambda (i x) (+ i x)) '(10 11)) '(10 12)))
    (should (lg-iany-of itr (lambda (i x) (= (+ i x) 12)) '(10 11)))
    (should (lg-inone-of itr (lambda (_i x) (< x 0)) '(1 2 3)))
    (should (lg-iall-of itr (lambda (i x) (>= (+ i x) 1)) '(1 2 3)))
    (should (= (lg-icount-of itr '(1 2 3 4)) 4))
    (should (equal (lg-review reviewer 9) '(:wrapped 9)))
    (should (equal (lg-reviews reviewer #'car 9) :wrapped))))

(ert-deftest lg-randomized-core-laws ()
  (let ((lens (lg-car))
        (prism (lg-non-nil))
        (traversal (lg-list)))
    (dotimes (_ 100)
      (let* ((pair (cons (lg-test--random-int) (lg-test--random-int)))
             (v1 (lg-test--random-int))
             (v2 (lg-test--random-int)))
        (should (equal (lg-set lens (lg-view lens pair) pair) pair))
        (should (equal (lg-view lens (lg-set lens v1 pair)) v1))
        (should (equal (lg-set lens v2 (lg-set lens v1 pair))
                       (lg-set lens v2 pair)))))

    (dotimes (_ 100)
      (let ((value (if (zerop (random 4)) nil (lg-test--random-int))))
        (should (equal (lg-preview prism (lg-review prism value)) value))
        (let ((previewed (lg-preview prism value)))
          (when previewed
            (should (equal (lg-review prism previewed) value))))))

    (dotimes (_ 100)
      (let* ((xs (lg-test--random-list))
             (f (lambda (x) (+ x 1)))
             (g (lambda (x) (* x 2))))
        (should (equal (lg-over traversal #'identity xs) xs))
        (should (equal (lg-over traversal (lambda (x) (funcall g (funcall f x))) xs)
                       (lg-over traversal g (lg-over traversal f xs))))))))

;;; looking-glass-test.el ends here
