;;; looking-glass-core-test.el --- Core tests for looking-glass -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'looking-glass)

(defun lg-test--random-int ()
  "Return a random integer in a small range for repeatable law tests."
  (- (random 200) 100))

(defun lg-test--random-list ()
  "Return a random list of integers."
  (let ((length (random 8))
        (result nil))
    (dotimes (_ length (nreverse result))
      (push (lg-test--random-int) result))))

(defun lg-test--random-string ()
  "Return a random lowercase ASCII string."
  (let ((length (random 16))
        (result nil))
    (dotimes (_ length (apply #'string (nreverse result)))
      (push (+ ?a (random 26)) result))))

(ert-deftest lg-lens-view-set-over ()
  (let ((optic lg-car))
    (should (equal (lg-view optic '(1 . 2)) 1))
    (should (equal (lg-set optic 9 '(1 . 2)) '(9 . 2)))
    (should (equal (lg-over optic (lambda (x) (+ x 3)) '(1 . 2)) '(4 . 2)))))

(ert-deftest lg-compose-nested-pairs ()
  (let* ((nested '((1 . 2) . 3))
         (optic (lg-compose lg-cdr lg-car)))
    (should (equal (lg-view optic nested) 2))
    (should (equal (lg-set optic 7 nested) '((1 . 7) . 3)))))

(ert-deftest lg-compose-operator-aliases ()
  (let ((nested '((1 . 2) . 3)))
    (should (equal (lg-view (lg<< lg-cdr lg-car) nested) 2))
    (should (equal (lg-view (lg>> lg-car lg-cdr) nested) 2))))

(ert-deftest lg-traversal-list-over-and-fold ()
  (let ((optic lg-list))
    (should (equal (lg-over optic (lambda (x) (* x 10)) '(1 2 3)) '(10 20 30)))
    (should (equal (lg-to-list-of optic '(1 2 3)) '(1 2 3)))))

(ert-deftest lg-prism-non-nil ()
  (let ((optic lg-non-nil))
    (should (equal (lg-preview optic 42) (lg-just 42)))
    (should (equal (lg-review optic 42) 42))
    (should (equal (lg-preview optic nil) lg-nothing))
    (should-not (lg-has optic nil))))

(ert-deftest lg-bool-and-unbool-helpers ()
  (should (eq (lg-bool-value lg-true) t))
  (should (eq (lg-bool-value lg-false) nil))
  (should (eq (lg-bool t) lg-true))
  (should (eq (lg-bool nil) lg-false))
  (should (eq (lg-view lg-unbool lg-true) t))
  (should (eq (lg-view lg-unbool lg-false) nil))
  (should (eq (lg-review lg-unbool t) lg-true))
  (should (eq (lg-review lg-unbool nil) lg-false))
  (should-error (lg-bool-value 'nope))
  (should-error (lg-bool 1)))

(ert-deftest lg-review-support ()
  (let* ((just lg-just-o)
         (iso (lg-iso #'number-to-string #'string-to-number))
         (composed (lg-compose just iso)))
    (should (equal (lg-review just 7) '(just . 7)))
    (should (equal (lg-review iso "42") 42))
    (should (equal (lg-review composed "9") '(just . 9)))
    (should-error (lg-review lg-list 1))))

(ert-deftest lg-reverse-reviewed-optics ()
  (let* ((iso (lg-iso #'number-to-string #'string-to-number))
         (reversed (lg-re iso)))
    (should (equal (lg-view reversed "42") 42))
    (should (equal (lg-review reversed 7) "7"))
    (should (equal (lg-over reversed (lambda (n) (+ n 1)) "41") "42"))
    (should-error (lg-re lg-list))))

(ert-deftest lg-convert-list-vector-iso ()
  (let ((optic lg-list->vector))
    (should (equal (lg-view optic '(1 2 3)) [1 2 3]))
    (should (equal (lg-review optic [1 2 3]) '(1 2 3)))
    (should (equal (lg-over optic (lambda (v) (vconcat v [4])) '(1 2 3)) '(1 2 3 4)))))

(ert-deftest lg-convert-number-string-prism ()
  (let ((optic lg-number-string))
    (should (equal (lg-preview optic "42") (lg-just 42)))
    (should (equal (lg-preview optic "  -3.5 ") (lg-just -3.5)))
    (should-not (lg-has optic "42x"))
    (should (equal (lg-review optic 15) "15"))))

(ert-deftest lg-convert-char-string-prism ()
  (let ((optic lg-char-string))
    (should (equal (lg-preview optic "A") (lg-just ?A)))
    (should-not (lg-has optic "AB"))
    (should (equal (lg-review optic ?Z) "Z"))))

(ert-deftest lg-convert-symbol-string-prism ()
  (let* ((existing (intern "lg-symbol-string-test"))
         (missing-name (format "lg-unknown-%s" (float-time)))
         (optic lg-symbol-string))
    (should (equal (lg-preview optic "lg-symbol-string-test") (lg-just existing)))
    (should-not (lg-has optic missing-name))
    (should (equal (lg-review optic 'hello) "hello"))))

(ert-deftest lg-convert-alist-plist-prism ()
  (let ((optic lg-alist-plist))
    (should (equal (lg-preview optic '((:a . 1) (:b . nil))) (lg-just '(:a 1 :b nil))))
    (should (equal (lg-review optic '(:a 1 :b nil)) '((:a . 1) (:b))))
    (should-not (lg-has optic '((:a . 1) (:a . 2))))
    (should-error (lg-review optic '(:a 1 :a 2)))))

(ert-deftest lg-either-core-and-prisms ()
  (should (lg-either-p (lg-left 1)))
  (should (lg-either-p (lg-right nil)))
  (should-not (lg-either-p 42))
  (should (= (lg-either-value (lg-left 5)) 5))

  (should (equal (lg-preview lg-left-o (lg-left 10)) (lg-just 10)))
  (should (equal (lg-preview lg-left-o (lg-left nil)) (lg-just nil)))
  (should (equal (lg-preview lg-left-o (lg-right 10)) lg-nothing))
  (should (equal (lg-review lg-left-o 7) (lg-left 7)))
  (should (equal (lg-over lg-left-o (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 3)))
  (should (equal (lg-over lg-left-o (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 2)))

  (should (equal (lg-preview lg-right-o (lg-right 10)) (lg-just 10)))
  (should (equal (lg-preview lg-right-o (lg-right nil)) (lg-just nil)))
  (should (equal (lg-preview lg-right-o (lg-left 10)) lg-nothing))
  (should (equal (lg-review lg-right-o 7) (lg-right 7)))
  (should (equal (lg-over lg-right-o (lambda (x) (+ x 1)) (lg-right 2)) (lg-right 3)))
  (should (equal (lg-over lg-right-o (lambda (x) (+ x 1)) (lg-left 2)) (lg-left 2))))

(ert-deftest lg-preview-disambiguates-present-nil ()
  (let* ((optic (lg-plist-key :name))
         (present-nil '(:name nil :age 10))
         (missing '(:age 10)))
    (should (equal (lg-preview optic present-nil) (lg-just nil)))
    (should (equal (lg-preview optic missing) lg-nothing))
    (should (lg-has optic present-nil))
    (should-not (lg-has optic missing))))

(ert-deftest lg-view-non-nil-signals ()
  (let ((optic (lg-plist-key :name)))
    (should-error (lg-view-non-nil optic '(:name nil)) :type 'lg-expected-non-nil)
    (should (equal (lg-view-non-nil optic '(:name "Ada")) "Ada"))))

(ert-deftest lg-alist-key ()
  (let ((optic (lg-alist-key "x" #'string=)))
    (should (equal (lg-preview optic '(("x" . nil) ("y" . 2))) (lg-just nil)))
    (should (equal (lg-over optic (lambda (_v) 9) '(("x" . nil) ("y" . 2)))
                   '(("x" . 9) ("y" . 2))))))

(ert-deftest lg-vector-and-string-traversals ()
  (should (equal (lg-over lg-vector (lambda (x) (+ x 1)) [1 2 3]) [2 3 4]))
  (should (equal (lg-over lg-string #'upcase "abc") "ABC"))
  (should (equal (lg-to-list-of lg-string "ab") '("a" "b"))))

(ert-deftest lg-indexed-vector-and-string-parity ()
  (should (equal (lg-ito-list-of lg-indexed-vector [10 20])
                 '((0 . 10) (1 . 20))))
  (should (equal (lg-iset lg-indexed-vector 0 [1 2 3]) [0 0 0]))
  (should (equal (lg-iover lg-indexed-vector (lambda (i x) (+ i x)) [10 10])
                 [10 11]))

  (should (equal (lg-ito-list-of lg-indexed-string "ab")
                 '((0 . "a") (1 . "b"))))
  (should (equal (lg-iover lg-indexed-string
                           (lambda (i ch)
                             (if (zerop i) (upcase ch) ch))
                           "ab")
                 "Ab")))

(ert-deftest lg-indexed-list-base-and-ops ()
  (let ((optic lg-indexed-list))
    (should (equal (lg-ito-list-of optic '(10 nil 30))
                   '((0 . 10) (1) (2 . 30))))
    (should (equal (lg-ipreview-maybe optic '(10 nil 30)) (lg-just '(0 . 10))))
    (should (equal (lg-ipreview-maybe optic '()) lg-nothing))
    (should (equal (lg-iover optic (lambda (i x) (if (= i 1) 99 x)) '(10 20 30))
                   '(10 99 30)))))

(ert-deftest lg-indexed-reindexing ()
  (let* ((base lg-indexed-list)
         (shifted (lg-ireindexed (lambda (index) (+ index 10)) base)))
    (should (equal (lg-ito-list-of shifted '(4 5)) '((10 . 4) (11 . 5))))
    (should (equal (lg-iover shifted (lambda (i x) (+ i x)) '(4 5)) '(14 16)))))

(ert-deftest lg-derived-getter-and-folds ()
  (let* ((getter (lg-getter #'length))
         (list-optic lg-list))
    (should (equal (lg-view getter '(a b c)) 3))
    (should (equal (lg-over getter (lambda (x) (+ x 1)) '(a b c)) '(a b c)))
    (should (= (lg-foldl-of list-optic #'+ 0 '(1 2 3 4)) 10))
    (should (= (lg-ifoldl-of lg-indexed-list
                             (lambda (acc i x) (+ acc (* i x)))
                             0
                             '(2 3 4))
               11))
    (should (lg-any-of list-optic (lambda (x) (= x 3)) '(1 2 3)))
    (should (lg-all-of list-optic (lambda (x) (> x 0)) '(1 2 3)))
    (should (= (lg-count-of list-optic '(1 2 3)) 3))))

(ert-deftest lg-filtered-and-indexed-combinators ()
  (let* ((even (lg-filtered (lambda (x) (and (numberp x) (zerop (% x 2))))) )
         (filtered-indexed (lg-indexed-list-indices (lambda (i) (zerop (% i 2)))))
         (i-only (lg-indices (lambda (i) (eq i nil)))))
    (should (equal (lg-over even (lambda (x) (* x 10)) 2) 20))
    (should (equal (lg-over even (lambda (x) (* x 10)) 3) 3))
    (should (equal (lg-ito-list-of filtered-indexed '(10 11 12 13))
                   '((0 . 10) (2 . 12))))
    (should (equal (lg-iover filtered-indexed (lambda (_i x) (+ x 1)) '(10 11 12 13))
                   '(11 11 13 13)))
    (should (equal (lg-ito-list-of i-only 99) '((nil . 99))))))

(ert-deftest lg-non-nil-helpers-and-macros ()
  (let* ((optic (lg-required (lg-plist-key :name)))
         (pair-optic (lg-optic lg-cdr lg-car)))
    (should (equal (lg-preview-or "unknown" optic '(:name "Ada")) "Ada"))
    (should (equal (lg-preview-or "unknown" optic '(:name nil)) "unknown"))
    (should (equal (lg-over lg-cdr
                            (lambda (x) (* x 2))
                            (lg-over lg-car
                                     (lambda (x) (+ x 10))
                                     '(1 . 2)))
                   '(11 . 4)))
    (should (equal (lg-set lg-cdr
                           9
                           (lg-set lg-car
                                   7
                                   '(1 . 2)))
                   '(7 . 9)))
    (should (equal (lg-view pair-optic '((1 . 2) . 3)) 2))))

(ert-deftest lg-extension-point-custom-affine-optic ()
  (let ((optic
         (lg-affine
          (lambda (source)
            (if (numberp source) (lg-just source) lg-nothing))
          (lambda (_source new-focus)
            (* 2 new-focus)))))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 10) 22))
    (should (equal (lg-over optic (lambda (x) (+ x 1)) 'nope) 'nope))
    (should (equal (lg-preview optic 10) (lg-just 10)))
    (should (equal (lg-preview optic 'nope) lg-nothing))))

(ert-deftest lg-ix-and-at-for-keyed-structures ()
  (let* ((plist '(:name nil :age 10))
         (alist '(("name" . nil) ("age" . 10)))
         (table (let ((h (make-hash-table :test 'equal)))
                  (puthash "name" nil h)
                  (puthash "age" 10 h)
                  h)))
    (should (equal (lg-preview (lg-ix :name) plist) (lg-just nil)))
    (should (equal (lg-preview (lg-ix :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-ix :name) "Ada" plist) '(:name "Ada" :age 10)))
    (should (equal (lg-set (lg-ix :missing) 1 plist) plist))

    (should (equal (lg-view (lg-at :name) plist) (lg-just nil)))
    (should (equal (lg-view (lg-at :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-at :missing) (lg-just 99) plist)
                   '(:name nil :age 10 :missing 99)))
    (should (equal (lg-set (lg-at :age) lg-nothing plist)
                   '(:name nil)))

    (should (equal (lg-view (lg-at-maybe :name) plist) (lg-just nil)))
    (should (equal (lg-view (lg-at-maybe :missing) plist) lg-nothing))
    (should (equal (lg-set (lg-at-maybe :missing) (lg-just 99) plist)
                   '(:name nil :age 10 :missing 99)))
    (should (equal (lg-set (lg-at-maybe :age) lg-nothing plist)
                   '(:name nil)))

    (should (equal (lg-preview (lg-ix "name" #'string=) alist) (lg-just nil)))
    (should (equal (lg-set (lg-at "missing" #'string=) (lg-just 7) alist)
                   '(("name") ("age" . 10) ("missing" . 7))))
    (should (equal (lg-set (lg-at "age" #'string=) lg-nothing alist)
                   '(("name"))))

    (should (equal (lg-preview (lg-ix "name") table) (lg-just nil)))
    (let ((updated (lg-set (lg-at "name") (lg-just "Ada") table)))
      (should (equal (gethash "name" updated) "Ada"))
      (should (= (hash-table-count updated) 2)))
    (let ((removed (lg-set (lg-at "age") lg-nothing table)))
      (should-not (gethash "age" removed))
      (should (= (hash-table-count removed) 1)))))

(ert-deftest lg-unmaybe-lossy-adapter-over-at ()
  (let* ((profile '(:name nil :age 10))
         (age-optic (lg-compose lg-unmaybe (lg-at :age)))
         (name-optic (lg-compose lg-unmaybe (lg-at :name))))
    (should (equal (lg-view age-optic profile) 10))
    (should (equal (lg-view name-optic profile) nil))
    (should (equal (lg-set age-optic nil profile) '(:name nil)))
    (should (equal (lg-set age-optic 42 profile) '(:name nil :age 42)))))

(ert-deftest lg-fold-review-and-indexed-combinators ()
  (let* ((tr lg-list)
         (itr lg-indexed-list)
         (reviewer (lg-unto (lambda (x) (list :wrapped x)))))
    (should (equal (lg-first-of tr '(4 5 6)) (lg-just 4)))
    (should (equal (lg-last-of tr '(4 5 6)) (lg-just 6)))
    (should (equal (lg-find-of tr (lambda (x) (> x 4)) '(1 3 5 7)) (lg-just 5)))
    (should (lg-none-of tr (lambda (x) (eq 1 (% x 2))) '(2 4 6)))
    (should (equal (lg-ifirst-of itr '(10 11)) (lg-just '(0 . 10))))
    (should (equal (lg-ilast-of itr '(10 11)) (lg-just '(1 . 11))))
    (should (equal (lg-ifind-of itr (lambda (i _x) (= i 1)) '(10 11 12)) (lg-just '(1 . 11))))
    (should (equal (lg-imap-of itr (lambda (i x) (+ i x)) '(10 11)) '(10 12)))
    (should (lg-iany-of itr (lambda (i x) (= (+ i x) 12)) '(10 11)))
    (should (lg-inone-of itr (lambda (_i x) (< x 0)) '(1 2 3)))
    (should (lg-iall-of itr (lambda (i x) (>= (+ i x) 1)) '(1 2 3)))
    (should (= (lg-icount-of itr '(1 2 3 4)) 4))
    (should (equal (lg-review reviewer 9) '(:wrapped 9)))
    (should (equal (lg-reviews reviewer #'car 9) :wrapped))))

(ert-deftest lg-indexed-helper-parity ()
  (let ((optic lg-indexed-list)
        (values '(nil 10 20)))
    (should (equal (lg-ipreview-or '(missing . missing) optic values)
                   '(0)))
    (should (equal (lg-ipreview-or '(missing . missing) optic '())
                   '(missing . missing)))
    (should (equal (lg-iview optic '(10 20)) '(0 . 10)))
    (should-error (lg-iview optic '()) :type 'lg-no-focus)
    (should (equal (lg-iview-non-nil optic '(10 20)) '(0 . 10)))
    (should-error (lg-iview-non-nil optic '(nil 20)) :type 'lg-expected-non-nil)
    (should (lg-ihas optic '(10)))
    (should-not (lg-ihas optic '()))
    (should (equal (lg-ifor-of optic '(10 10)
                               (lambda (i x) (+ i x)))
                   '(10 11)))))

(ert-deftest lg-indexed-unindexed-bridges ()
  (let ((plain lg-list)
        (indexed lg-indexed-list))
    (should (equal (lg-ito-list-of (lg-as-indexed plain) '(4 5))
                   '((nil . 4) (nil . 5))))
    (should (equal (lg-over (lg-unindexed indexed) (lambda (x) (+ x 1)) '(4 5))
                   '(5 6)))))

(ert-deftest lg-randomized-core-laws ()
  (let ((lens lg-car)
        (prism lg-non-nil)
        (traversal lg-list))
    (dotimes (_ 100)
      (let* ((pair (cons (lg-test--random-int) (lg-test--random-int)))
             (v1 (lg-test--random-int))
             (v2 (lg-test--random-int)))
        (should (equal (lg-set lens (lg-view lens pair) pair) pair))
        (should (equal (lg-view lens (lg-set lens v1 pair)) v1))
        (should (equal (lg-set lens v2 (lg-set lens v1 pair))
                       (lg-set lens v2 pair)))))

    (dotimes (_ 100)
      (let ((value (if (zerop (random 4)) nil (lg-test--random-int))))
        (should (equal (lg-preview prism (lg-review prism value))
                       (if value (lg-just value) lg-nothing)))
        (let ((previewed (lg-preview prism value)))
          (when (lg-just-p previewed)
            (should (equal (lg-review prism (cdr previewed)) value))))))

    (dotimes (_ 100)
      (let* ((xs (lg-test--random-list))
             (f (lambda (x) (+ x 1)))
             (g (lambda (x) (* x 2))))
        (should (equal (lg-over traversal #'identity xs) xs))
        (should (equal (lg-over traversal (lambda (x) (funcall g (funcall f x))) xs)
                       (lg-over traversal g (lg-over traversal f xs))))))))

(ert-deftest lg-randomized-keyed-optics-laws ()
  (dolist (kind '(plist alist hash))
    (dotimes (_ 100)
      (let* ((present (zerop (random 2)))
             (value (if (zerop (random 4)) nil (lg-test--random-int)))
             (replacement (if (zerop (random 4)) nil (lg-test--random-int)))
             (key (if (eq kind 'plist) :k "k"))
             (testfn (if (eq kind 'alist) #'string= nil))
             (source
              (pcase kind
                ('plist (if present
                            (list :k value :other 1)
                          (list :other 1)))
                ('alist (if present
                            (list (cons "k" value) (cons "other" 1))
                          (list (cons "other" 1))))
                ('hash (let ((table (make-hash-table :test 'equal)))
                         (when present
                           (puthash "k" value table))
                         (puthash "other" 1 table)
                         table))))
             (ix (lg-ix key testfn))
             (at (lg-at key testfn))
             (at-maybe (lg-at-maybe key testfn)))
        (should (equal (lg-has ix source) present))
        (should (equal (lg-view at source)
                       (if present (lg-just value) lg-nothing)))
        (should (equal (lg-view at-maybe source)
                       (if present (lg-just value) lg-nothing)))

        (let ((ix-updated (lg-set ix replacement source)))
          (should (equal (lg-preview ix ix-updated)
                         (if present (lg-just replacement) lg-nothing))))

        (let ((at-updated (lg-set at (lg-just replacement) source)))
          (should (equal (lg-preview ix at-updated)
                         (lg-just replacement))))

        (let ((at-removed (lg-set at lg-nothing source)))
          (should (equal (lg-preview ix at-removed) lg-nothing)))))))

(ert-deftest lg-randomized-vector-and-string-traversal-laws ()
  (let ((vector-optic lg-vector)
        (string-optic lg-string))
    (dotimes (_ 100)
      (let* ((xs (lg-test--random-list))
             (vec (vconcat xs))
             (f (lambda (x) (+ x 1)))
             (g (lambda (x) (* x 2))))
        (should (equal (lg-over vector-optic #'identity vec) vec))
        (should (equal (lg-over vector-optic (lambda (x) (funcall g (funcall f x))) vec)
                       (lg-over vector-optic g (lg-over vector-optic f vec))))))

    (dotimes (_ 100)
      (let ((s (lg-test--random-string)))
        (should (equal (lg-over string-optic #'identity s) s))
        (should (equal (lg-over string-optic #'upcase s)
                       (upcase s)))))))

(ert-deftest lg-nth-supports-lists-vectors-and-strings ()
  (let ((optic (lg-nth 1)))
    (should (equal (lg-view optic '(4 5 6)) 5))
    (should (equal (lg-set optic 9 '(4 5 6)) '(4 9 6)))
    (should (equal (lg-view optic [4 5 6]) 5))
    (should (equal (lg-set optic 9 [4 5 6]) [4 9 6]))
    (should (equal (lg-view optic "abcd") ?b))
    (should (equal (lg-set optic ?Z "abcd") "aZcd"))
    (should-error (lg-set optic "Z" "abcd"))
    (should-error (lg-view optic 'foo))
    (should-error (lg-view (lg-nth 9) [1 2]))))

(ert-deftest lg-json-parse-default-prism-roundtrip-and-edit ()
  (let ((json "{\"name\":\"Ada\",\"tags\":[\"elisp\",\"optics\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (should (equal
             (lg-over (lg-compose (lg-ix "name") lg-json-parse) #'upcase json)
             "{\"name\":\"ADA\",\"tags\":[\"elisp\",\"optics\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (should (equal
             (lg-over (lg-compose (lg-ix "tags") lg-json-parse)
                      (lambda (tags)
                        (let ((copy (copy-sequence tags)))
                          (aset copy 1 (upcase (aref copy 1)))
                          copy))
                      json)
             "{\"name\":\"Ada\",\"tags\":[\"elisp\",\"OPTICS\"],\"active\":true,\"disabled\":false,\"note\":null}"))
    (let ((parsed (lg-view lg-json-parse json)))
      (should (eq (gethash "active" parsed) lg-true))
       (should (eq (gethash "disabled" parsed) lg-false))
       (should (null (gethash "note" parsed))))))

(ert-deftest lg-json-parse-custom-with-args ()
  (let* ((prism (lg-json-parse-with 'alist 'list nil lg-false))
         (json "{\"ok\":true,\"nope\":false,\"items\":[1,2]}")
         (value (lg-view prism json)))
    (should (equal value '((ok . lg-true) (nope . lg-false) (items 1 2))))
    (should (equal (lg-review prism value) json))))

(ert-deftest lg-json-parse-prism-fails-gracefully ()
  (let ((bad "{\"missing\":true")
        (optic (lg-json-parse-with 'hash-table 'array nil lg-false)))
    (should (equal (lg-preview optic bad) lg-nothing))
    (should-error (lg-view optic bad))
    (should (equal (lg-over optic #'identity bad) bad))))

(provide 'looking-glass-core-test)

;;; looking-glass-core-test.el ends here
